from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils import timezone

from activities.choices import ContentStatus
from activities.models import DevelopmentalActivity
from profiles.models import ChildProfile


class Recommendation(models.Model):
    """An activity recommended to a child, with the scores that ranked it.

    The explanation is generated by the explainability module (Sprint 6).
    """

    child = models.ForeignKey(
        ChildProfile, on_delete=models.CASCADE, related_name="recommendations"
    )
    # PROTECT keeps recommendation history intact; retire activities by
    # unpublishing them instead of deleting. Only published activities can be
    # chosen when a recommendation is validated.
    activity = models.ForeignKey(
        DevelopmentalActivity,
        on_delete=models.PROTECT,
        related_name="recommendations",
        limit_choices_to={"content_status": ContentStatus.PUBLISHED},
    )
    similarity_score = models.FloatField(
        validators=[MinValueValidator(-1.0), MaxValueValidator(1.0)],
        help_text="Cosine similarity between profile and activity embeddings.",
    )
    ranking_score = models.FloatField(
        help_text="Weighted score combining rule priority and semantic similarity."
    )
    explanation = models.TextField(blank=True)
    date_generated = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ["-date_generated", "-ranking_score"]
        constraints = [
            models.CheckConstraint(
                condition=models.Q(similarity_score__gte=-1.0)
                & models.Q(similarity_score__lte=1.0),
                name="similarity_score_between_-1_and_1",
            ),
        ]

    def __str__(self):
        return f"{self.activity.activity_name} for {self.child}"


class ActivityEmbedding(models.Model):
    """Precomputed SBERT embedding of a Published activity (DR-09, DR-10).

    Stored as float32 bytes. text_hash records the model and text that were
    embedded, so embed_activities only re-encodes activities that changed.
    """

    activity = models.OneToOneField(
        DevelopmentalActivity, on_delete=models.CASCADE, related_name="embedding"
    )
    model_name = models.CharField(max_length=100)
    dimensions = models.PositiveSmallIntegerField()
    text_hash = models.CharField(max_length=64)
    vector = models.BinaryField()
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.model_name} embedding of {self.activity.activity_id}"
