# Generated by Django 6.1.1 on 2026-09-29 16:24

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DevelopmentalActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_id",
                    models.CharField(
                        help_text="Dataset ID, e.g. ACT001.", max_length=20, unique=True
                    ),
                ),
                ("activity_name", models.CharField(max_length=200)),
                (
                    "developmental_domain",
                    models.CharField(
                        choices=[
                            ("Cognitive", "Cognitive"),
                            ("Language", "Language"),
                            ("Motor", "Motor"),
                            ("Sensory", "Sensory"),
                            ("Socio-Emotional", "Socio-Emotional"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "age_range",
                    models.CharField(
                        choices=[
                            ("Prenatal", "Prenatal"),
                            ("0-3 months", "0-3 months"),
                            ("3-6 months", "3-6 months"),
                            ("6-12 months", "6-12 months"),
                            ("12-18 months", "12-18 months"),
                            ("18-24 months", "18-24 months"),
                            ("24-36 months", "24-36 months"),
                        ],
                        max_length=20,
                    ),
                ),
                ("developmental_goal", models.TextField()),
                (
                    "materials",
                    models.TextField(help_text='Use "None" if nothing is required.'),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("Beginner", "Beginner"),
                            ("Intermediate", "Intermediate"),
                            ("Advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("cultural_relevance", models.TextField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("WHO", "WHO"),
                            ("CDC", "CDC"),
                            ("UNICEF", "UNICEF"),
                            ("Montessori", "Montessori"),
                            ("Pathways.org", "Pathways.org"),
                        ],
                        help_text="Organisation whose guidance this activity is traceable to.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "developmental activities",
                "ordering": ["activity_id"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("activity_name"),
                        models.F("developmental_domain"),
                        name="unique_activity_name_per_domain",
                    )
                ],
            },
        ),
    ]
