# Generated by Django 6.1.1 on 2026-09-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="developmentalactivity",
            name="content_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("under_review", "Under Review"),
                    ("published", "Published"),
                ],
                default="draft",
                help_text="Only published activities are recommended.",
                max_length=20,
            ),
        ),
    ]
