# Generated by Django 6.1.1 on 2026-09-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_developmentalactivity_content_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="developmentalactivity",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="Link to the specific guidance document, once verified.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="developmentalactivity",
            name="activity_id",
            field=models.CharField(
                help_text="Dataset ID, e.g. ACT-0001.", max_length=20, unique=True
            ),
        ),
    ]
