# Generated by Django 6.1.1 on 2026-10-10 14:46

import activities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0003_developmentalactivity_source_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="developmentalactivity",
            name="plain_aim",
            field=models.CharField(
                blank=True,
                help_text='Completes "Its aim is to ...": second person, at most 20 words, no technical terms, British spelling. Leave blank to show no aim sentence.',
                max_length=200,
                validators=[activities.models.validate_plain_aim],
            ),
        ),
    ]
