# Generated by Django 6.1.1 on 2026-09-29 17:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activities", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(
                        help_text="Cosine similarity between profile and activity embeddings.",
                        validators=[
                            django.core.validators.MinValueValidator(-1.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "ranking_score",
                    models.FloatField(
                        help_text="Weighted score combining rule priority and semantic similarity."
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                (
                    "date_generated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendations",
                        to="activities.developmentalactivity",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="profiles.childprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_generated", "-ranking_score"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("similarity_score__gte", -1.0),
                            ("similarity_score__lte", 1.0),
                        ),
                        name="similarity_score_between_-1_and_1",
                    )
                ],
            },
        ),
    ]
