# Generated by Django 6.1.1 on 2026-09-29 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_developmentalactivity_content_status"),
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendation",
            name="activity",
            field=models.ForeignKey(
                limit_choices_to={"content_status": "published"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recommendations",
                to="activities.developmentalactivity",
            ),
        ),
    ]
