# Generated by Django 6.1.1 on 2026-10-02 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0003_developmentalactivity_source_url"),
        ("recommendations", "0002_alter_recommendation_activity"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("dimensions", models.PositiveSmallIntegerField()),
                ("text_hash", models.CharField(max_length=64)),
                ("vector", models.BinaryField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="activities.developmentalactivity",
                    ),
                ),
            ],
        ),
    ]
