# Generated by Django 6.1.1 on 2026-10-10 09:41

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0003_developmentalactivity_source_url"),
        ("profiles", "0005_developmental_profile"),
        ("recommendations", "0003_activity_embedding"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recommendation",
            options={"ordering": ["-date_generated", "-ranking_score", "position"]},
        ),
        migrations.AddField(
            model_name="recommendation",
            name="age_weight",
            field=models.FloatField(
                default=1.0,
                help_text="How well the activity's age range suits the child.",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="alpha",
            field=models.FloatField(
                default=0.0,
                help_text="Weight of rule priority used for this batch.",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="batch",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="position",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="profile_fingerprint",
            field=models.CharField(
                blank=True,
                help_text="Hash of the rule-engine output, age bracket and milestone catalogue the batch was ranked from.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="ranking_version",
            field=models.CharField(
                blank=True,
                help_text="Hash of the ranking configuration (weights, settings, alpha, model).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="rule_priority",
            field=models.FloatField(
                default=0.0,
                help_text="Rule-engine priority of the activity's domain (top = 1).",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="ranking_score",
            field=models.FloatField(
                help_text="Weighted score combining rule priority and semantic similarity.",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="similarity_score",
            field=models.FloatField(
                help_text="Raw cosine similarity between profile and activity embeddings.",
                validators=[
                    django.core.validators.MinValueValidator(-1.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ranking_score__gte", 0.0), ("ranking_score__lte", 1.0)
                ),
                name="ranking_score_between_0_and_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rule_priority__gte", 0.0), ("rule_priority__lte", 1.0)
                ),
                name="rule_priority_between_0_and_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendation",
            constraint=models.CheckConstraint(
                condition=models.Q(("age_weight__gte", 0.0), ("age_weight__lte", 1.0)),
                name="age_weight_between_0_and_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendation",
            constraint=models.CheckConstraint(
                condition=models.Q(("alpha__gte", 0.0), ("alpha__lte", 1.0)),
                name="alpha_between_0_and_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendation",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1), ("position__lte", 5)),
                name="position_between_1_and_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendation",
            constraint=models.UniqueConstraint(
                fields=("batch", "position"), name="unique_position_per_batch"
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendation",
            constraint=models.UniqueConstraint(
                fields=("batch", "activity"), name="unique_activity_per_batch"
            ),
        ),
    ]
