# Generated by Django 6.1.1 on 2026-10-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0004_recommendation_batches"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="explanation_version",
            field=models.CharField(
                blank=True,
                help_text="Version of the explanation wording that produced the text (blank for batches stored before explanations, #69).",
                max_length=20,
            ),
        ),
    ]
