# Generated by Django 6.1.1 on 2026-09-29 18:53

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", profiles.models.NurturaUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("caregiver", "Caregiver"),
                    ("administrator", "Administrator"),
                ],
                default="caregiver",
                max_length=20,
            ),
        ),
    ]
