# Generated by Django 6.1.1 on 2026-09-29 19:26

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("profiles", "0002_alter_user_managers_user_role"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(("email", ""), _negated=True),
                name="unique_user_email_case_insensitive",
                violation_error_message="A user with this email already exists.",
            ),
        ),
    ]
