# Generated by Django 6.1.1 on 2026-10-01 19:32

import django.db.models.deletion
import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_user_unique_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferenceMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "milestone_key",
                    models.CharField(
                        help_text="e.g. CDC-12M-LA-01 or WHO-MO-06.",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("WHO", "WHO"),
                            ("CDC", "CDC"),
                            ("UNICEF", "UNICEF"),
                            ("Montessori", "Montessori"),
                            ("Pathways.org", "Pathways.org"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "expected_age_months",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Age by which the guideline expects the milestone.",
                        max_digits=4,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("Cognitive", "Cognitive"),
                            ("Language", "Language"),
                            ("Motor", "Motor"),
                            ("Sensory", "Sensory"),
                            ("Socio-Emotional", "Socio-Emotional"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("source_reference", models.CharField(max_length=300)),
                ("notes", models.TextField(blank=True)),
                (
                    "verified",
                    models.BooleanField(
                        default=False, help_text="Checked against the source document."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["expected_age_months", "milestone_key"],
            },
        ),
        migrations.AddField(
            model_name="childprofile",
            name="concerns",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Domains the caregiver is concerned about, e.g. ["Sensory"].',
                validators=[profiles.models.validate_domain_list],
            ),
        ),
        migrations.AddField(
            model_name="developmentalmilestone",
            name="reference",
            field=models.ForeignKey(
                blank=True,
                help_text="Guideline milestone this observation is for, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="observations",
                to="profiles.referencemilestone",
            ),
        ),
    ]
