# Generated by Django 6.1.1 on 2026-10-01 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_reference_milestones_and_concerns"),
    ]

    operations = [
        migrations.CreateModel(
            name="DevelopmentalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age_months",
                    models.FloatField(
                        help_text="Age when generated; negative for prenatal profiles.",
                        null=True,
                    ),
                ),
                (
                    "scores",
                    models.JSONField(
                        default=dict,
                        help_text="Priority per domain, 0-1 (top domain = 1).",
                    ),
                ),
                ("ranked_domains", models.JSONField(default=list)),
                (
                    "reasons",
                    models.JSONField(
                        default=list,
                        help_text="Rules that fired, with sources and reasons.",
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developmental_profile",
                        to="profiles.childprofile",
                    ),
                ),
            ],
        ),
    ]
